version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mc_webapi
    ports:
      - "3000:3000"
    volumes:
      - .:/MinecraftServerAPI
    links:
      - mc_serv:mcserv

  mcserv:
    image: itzg/minecraft-server
    environment: 
      EULA: true
      ENABLE_RCON: true
      RCON_PASSWORD: rcon
      ONLINE_MODE: false
    container_name: mc_serv
    volumes:
      - ./world:/world
    ports:
      - "25565:25565"

  prom:
    image: prom/prometheus
    container_name: mc_prom
    volumes:
      - ./prometheus/:/etc/prometheus/
    ports:
      - "9090:9090"

  minecraft-exporter:
    build: https://github.com/Joshi425/minecraft-exporter.git
    container_name: mc_exporter
    environment:
      RCON_HOST: mcserv
      RCON_PORT: "25575"
      RCON_PASSWORD: rcon
    ports:
    - "9700:8000"
    volumes:
    - ./world:/world:ro

