global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'minecraft_exporter'
    static_configs:
      - targets: ['mc_exporter:8000']

  - job_name: 'minecraft_other_exporter'
    static_configs:
      - targets: ['mc_other_exporter:9150']
  
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']